rbac: true
global:
  cattle:
    url: https://support.rancher.cloud/
controller:
  replicas: 3
  ranchersso:
    enabled: true
  env:
    - name: CTRL_EN_ICMP_POLICY
      value: "1"
  affinity: {}
  pvc:
    enabled: true
    storageClass: longhorn
    capacity: 3G
manager:
  svc:
    type: ClusterIP
  env:
    ssl: false
cve:
  scanner:
    replicas: 1
