apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root-app
  namespace: argo
spec:
  project: default
  destination:
    namespace: argo
    name: home-cluster-rke
  source:
    repoURL: https://github.com/rajeshkio/my-lab-setup.git 
    path: argocd
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - allowEmpty=true
      - CreateNamespace=true
      - Replace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
