apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homer-ingressroute
  namespace: homer-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`homer.rajesh-kumar.in`)
    kind: Rule
    services:
    - name: homer-app
      port: 8080
      scheme: http
  tls:
    secretName: rancher-tls-cert
