apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nv-secret
  namespace: cattle-neuvector-system
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: neuvector-init
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: neuvector-init
          # here you define the keys that should be used as template
          items:
          - key: userinitcfg.yaml
  data:
  - secretKey: CTRL_PASSWORD 
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/neuvector
      metadataPolicy: None
      property: adminPass
  - secretKey: CTRL_USERNAME
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/neuvector
      metadataPolicy: None
      property: adminUser
  - secretKey: USERONE_PASS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/neuvector
      metadataPolicy: None
      property: userOnePass
