deployment:
  kind: DaemonSet
service:
  externalIPs:
    - 192.168.1.102
    - 192.168.1.101
additionalArguments:
 - "--serversTransport.insecureSkipVerify=true" 
logs:
  general:
    level: DEBUG
  access:
    enabled: true
    format: json
