apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: grafana-creds-secret
    creationPolicy: Owner
  data:
  - secretKey: GF_SECURITY_ADMIN_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/grafana
      metadataPolicy: None
      property: adminPassword
  - secretKey: GF_SECURITY_ADMIN_USER
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/grafana
      metadataPolicy: None
      property: adminUser
  - secretKey: GF_AUTH_GITHUB_CLIENT_ID 
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/grafana
      metadataPolicy: None
      property: githubClientID
  - secretKey: GF_AUTH_GITHUB_CLIENT_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/grafana
      metadataPolicy: None
      property: githubClientSecret
  - secretKey: thanos_receive_user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/grafana
      metadataPolicy: None
      property: prom_thanos_auth_user
  - secretKey: thanos_receive_pass
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/grafana
      metadataPolicy: None
      property: prom_thanos_auth_pass
