apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanagerconfig
  namespace: monitoring
spec:
  receivers:
  - emailConfigs:
    - authPassword:
        key: test-app-password
        name: smtp-pass
      authUsername: rk90229@gmail.com
      from: rk90229@gmail.com
      requireTLS: true
      sendResolved: true
      smarthost: smtp.gmail.com:587
      tlsConfig:
        serverName: smtp.gmail.com:587
      to: srk280392@gmail.com
    name: test-smtp
  route:
    groupInterval: 30s
    groupWait: 5m
    receiver: test-smtp
    repeatInterval: 4h
