apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nv-exporter-secret
  namespace: cattle-neuvector-system
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: neuvector-prometheus-exporter-pod-secret
    creationPolicy: Owner
  data:
  - secretKey: CTRL_PASSWORD 
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/neuvector
      metadataPolicy: None
      property: adminPass
  - secretKey: CTRL_USERNAME
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/neuvector
      metadataPolicy: None
      property: adminUser
  - secretKey: ENFORCER_STATS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/neuvector
      metadataPolicy: None
      property: ENFORCER_STATS
