k3s:
  enabled: "true"
global:
  cattle:
    url: https://rancher.rajesh-kumar.in
controller:
  ranchersso:
    enabled: "true"
  apisvc:
    type: NodePort
  federation:
    mastersvc:
      type: ClusterIP
  env:
    - name: CTRL_EN_ICMP_POLICY
      value: "1"
  pvc:
    enabled: true
    storageClass: longhorn
    capacity: 5Gi
  affinity: []
enforcer:
  env:
    - name: NV_SYSTEM_GROUPS
      value: "*cattle-cluster*;*fleet-agent*"
manager:
  svc:
    type: ClusterIP
  env:
    ssl: "true"
