clusterDomain: practice-cluster.local
prometheus:
  externalLabels:
    cluster: "practice-cluster"
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: 'neuvector-practice-cluster'
          scrape_interval: 30s
          scrape_timeout: 10s
          static_configs:
            - targets: ['neuvector-prometheus-exporter.cattle-neuvector-system.svc.cluster.local:8068']
              labels:
                cluster: 'practice-cluster'
  remoteWrite:
    - url: https://thanos.rajesh-kumar.in/api/v1/receive
      basicAuth:
        username:
          name: thanos-creds-secret
          key: thanos_receive_user
        password:
          name: thanos-creds-secret
          key: thanos_receive_pass
alertmanager:
  secrets:
    - smtp-pass
  config:
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
    receivers:
      - name: alert-emailer
        email_configs:
          - to: rk90229@gmail.com
            send_resolved: true
            from: rk90229@gmail.com
            smarthost: smtp.gmail.com:587
            require_tls: true
            auth_password:
              key: test-app-password
              name: smtp-pass
            auth_username: rk90229@gmail.com
