apiVersion: traefik.io/v1alpha1 
kind: IngressRoute
metadata:
  name: argocd-https
  namespace: argo
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`argo.rajesh-kumar.in`)
    kind: Rule
    services:
    - name: argo-argocd-server
      port: http
  - match: Host(`argo.rajesh-kumar.in`) && PathPrefix(`/api/webhook`)
    kind: Rule
    services:
    - name: argo-argocd-applicationset-controller
      port: 7000
  - kind: Rule
    match: Host(`argo-grpc.rajesh-kumar.in`) && Header(`Content-Type`, `application/grpc`)
    services:
      - name: argo-argocd-server
        port: 80
        scheme: h2c
  tls:
    secretName: rancher-tls-cert 
