apiVersion: v1
kind: Secret
metadata:
  name: practice-cluster-secret
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: practice-cluster
  server: https://rancher.rajesh-kumar.in/k8s/clusters/defhvegivgv
  config: |
    {
      "bearerToken": "token-sdkcdvjioerhedvruvbeview",
      "tlsClientConfig": {
        "insecure": false
      }
    }
