apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-secret
  namespace: argo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: webhook-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: github_webhook_secret
    remoteRef:
      key: secret/argo/webhook
      property: github_webhook_secret
