clusterDomain: home-cluster.local
prometheus:
  externalLabels:
    cluster: "home-cluster"
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: 'argocd-home-cluster'
          scrape_interval: 30s
          scrape_timeout: 10s
          static_configs:
            - targets: ['argo-argocd-server-metrics.argo.svc.cluster.local:8083','argo-argocd-application-controller-metrics.argo.svc.cluster.local:8082','argo-argocd-notifications-controller-metrics.argo.svc.cluster.local:9001','argo-argocd-server-metrics.argo.svc.cluster.local:8083','argo-argocd-redis-metrics.argo.svc.cluster.local:9121']
              labels:
                cluster: 'home-cluster'
  remoteWrite:
    - url: https://thanos.rajesh-kumar.in/api/v1/receive
      basicAuth:
        username:
          name: thanos-creds-secret
          key: thanos_receive_user
        password:
          name: thanos-creds-secret
          key: thanos_receive_pass
