apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets
  namespace: argo
spec:
  generators:
  - list:
      elements:
#        - cluster: local-cluster
#          app-name: prometheus
#          namespace: monitoring
#        - cluster: home-cluster-raspi
#          app-name: prometheus
#          namespace: monitoring
#        - cluster: home-cluster-raspi
#          app-name: grafana
#          namespace: monitoring
#        - cluster: home-cluster-rke
#          app-name: prometheus
#          namespace: monitoring
        - cluster: home-cluster-rke
          app-name: neuvector
          namespace: cattle-neuvector-system
        - cluster: home-cluster-rke
          app-name: nv-monitor
          namespace: cattle-neuvector-system
#        - cluster: local-cluster
#          app-name: thanos
#          namespace: monitoring
  template:
    metadata:
      name: '{{cluster}}-{{app-name}}-externalsecret'
      namespace: argo
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
        name: '{{cluster}}'
      source:
        repoURL: https://github.com/rajeshkio/my-lab-setup.git
        path: 'applications/{{cluster}}/{{app-name}}/externalSecret'
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
