apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets
  namespace: argo
spec:
  generators:
  - list:
      elements:
        - cluster: practice-cluster
          app-name: prometheus
          namespace: monitoring
        - cluster: local-cluster
          app-name: prometheus
          namespace: monitoring
        - cluster: home-cluster
          app-name: prometheus
          namespace: monitoring
        - cluster: local-cluster
          app-name: thanos
          namespace: monitoring
        - cluster: practice-cluster
          app-name: grafana
          namespace: monitoring
        - cluster: practice-cluster
          app-name: neuvector
          namespace: cattle-neuvector-system
        - cluster: practice-cluster
          app-name: nv-monitor
          namespace: cattle-neuvector-system
  template:
    metadata:
      name: '{{app-name}}-{{cluster}}-external-secret'
      namespace: argo
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
        name: '{{cluster}}'
      source:
        repoURL: https://github.com/rk280392/my-lab-setup.git
        path: 'applications/{{cluster}}/{{app-name}}/externalSecret'
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - Replace=true
        automated:
          prune: true
          selfHeal: true
