apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: configmaps
  namespace: argo
spec:
  generators:
  - list:
      elements:
        - cluster: local-cluster
          app-name: thanos
          cluster-name: in-cluster
          namespace: monitoring
        - cluster: practice-cluster
          app-name: grafana
          cluster-name: practice-cluster
          namespace: monitoring
        - cluster: practice-cluster
          app-name: neuvector
          cluster-name: practice-cluster
          namespace: cattle-neuvector-system
  template:
    metadata:
      name: '{{app-name}}-{{cluster-name}}-cm'
      namespace: argo
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
        name: '{{cluster-name}}'
      source:
        repoURL: https://github.com/rk280392/my-lab-setup.git
        path: 'applications/{{cluster}}/{{app-name}}/configmaps'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
