apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: configmaps
  namespace: argo
spec:
  generators:
  - list:
      elements:
#        - cluster: local-cluster
#          app-name: thanos
#          namespace: monitoring
#        - cluster: home-cluster-raspi
#          app-name: grafana
#          namespace: monitoring
        - cluster: local-cluster
          app-name: neuvector
          namespace: cattle-neuvector-system
  template:
    metadata:
      name: '{{cluster}}-{{app-name}}-cm'
      namespace: argo
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
        name: '{{cluster}}'
      source:
        repoURL: https://github.com/rajeshkio/my-lab-setup.git
        path: 'applications/{{cluster}}/{{app-name}}/configmaps'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
