apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-prom-externalsecret
  namespace: monitoring
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: thanos-creds-secret
    creationPolicy: Owner
  data:
  - secretKey: thanos_receive_user
    remoteRef:
      key: secret/grafana
      property: prom_thanos_auth_user
  - secretKey: thanos_receive_pass
    remoteRef:
      key: secret/grafana
      property: prom_thanos_auth_pass
