k3s:
  enabled: "true"
global:
  cattle:
    url: https://rancher.rajesh-kumar.in
controller:
  ranchersso:
    enabled: "true"
  apisvc:
    type: NodePort
  federation:
    mastersvc:
      type: ClusterIP
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: NotIn
                values:
                  - arm64
manager:
  svc:
    type: ClusterIP
  env:
    ssl: "true"
