clusterDomain: local-cluster.local
prometheus:
  externalLabels:
    cluster: "local-cluster"
  additionalScrapeConfigs:
    enabled: true
    type: external
    external:
      name: "nginx-exporter"
      key: "prometheus-nginx.yaml"

  remoteWrite:
    - url: https://thanos.rajesh-kumar.in/api/v1/receive
      basicAuth:
        username:
          name: thanos-creds-secret
          key: thanos_receive_user
        password:
          name: thanos-creds-secret
          key: thanos_receive_pass
configSelector:
  matchLabels:
    alertmanagerConfig: alertmanagerconfig
