clusterDomain: local-cluster.local
operator:
  containerSecurityContext:
    seLinuxOptions: {}
  prometheusConfigReloader:
    containerSecurityContext:
      seLinuxOptions: {}
prometheus:
  resources:
    limits:
      memory: 4000Mi
    requests:
      memory: 2000Mi
  containerSecurityContext:
    seLinuxOptions: {}
  externalLabels:
    cluster: "local-cluster"
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: 'local-cluster'
          scrape_interval: 30s
          scrape_timeout: 10s
          static_configs:
            - targets: ['local-cluster-prometheus-kube-state-metrics.monitoring.svc.cluster.local:8080']
              labels:
                cluster: 'local-cluster'
  remoteWrite:
    - url: https://thanos.rajesh-kumar.in/api/v1/receive
      basicAuth:
        username:
          name: thanos-creds-secret
          key: thanos_receive_user
        password:
          name: thanos-creds-secret
          key: thanos_receive_pass
alertmanager:
  containerSecurityContext:
    seLinuxOptions: {}
  configSelector:
    matchLabels:
      alertmanagerConfig: alertmanagerconfig
blackboxExporter:
  containerSecurityContext:
    seLinuxOptions: {}
