clusterDomain: local-cluster.local
prometheus:
  externalLabels:
    cluster: "local-cluster"
  remoteWrite:
    - url: https://thanos.rajesh-kumar.in/api/v1/receive
      basicAuth:
        username:
          name: thanos-creds-secret
          key: thanos_receive_user
        password:
          name: thanos-creds-secret
          key: thanos_receive_pass
