receive:
  replicaCount: 1
  enabled: "true"
  logLevel: debug
  tsdbRetention: 2d
  resources:
    limits:
      cpu: 150m
      ephemeral-storage: 1Gi
      memory: 5020Mi
    requests:
      cpu: 100m
      ephemeral-storage: 50Mi
      memory: 1024Mi

existingObjstoreSecret: "thanos-obj-secret"
queryFrontend:
  resources:
    limits:
      memory: "512Mi"
      cpu: "0.5"
minio:
  enabled: true
  metrics:
    serviceMonitor:
      enabled: true
      namespace: monitoring
  resources:
    limits:
      cpu: 375m
      ephemeral-storage: 1Gi
      memory: 1000Mi
    requests:
      cpu: 250m
      ephemeral-storage: 50Mi
      memory: 512Mi
query:
  resources:
    limits:
      memory: "512Mi"
      cpu: "0.5"
ruler:
  resources:
    limits:
      memory: "512Mi"
      cpu: "0.5"
storeGateway:
  resources:
    limits:
      memory: "512Mi"
      cpu: "0.5"
metrics:
  enabled: "true"
prometheusRule:
  enabled: "true"
  namespace: "monitoring"
