receive:
  enabled: "true"
  nodeSelector:
    kubernetes.io/hostname: raspberrypi-1
existingObjstoreSecret: "thanos-obj-secret"
metrics:
  enabled: "true"
  prometheusRule:
    enabled: "true"
    namespace: "monitoring"

