receive:
  enabled: "true"
  logLevel: info
  tsdbRetention: 2d
existingObjstoreSecret: "thanos-obj-secret"
queryFrontend:
  resources:
    limits:
      memory: "512Mi"
      cpu: "0.5"
query:
  resources:
    limits:
      memory: "512Mi"
      cpu: "0.5"
ruler:
  resources:
    limits:
      memory: "512Mi"
      cpu: "0.5"
storeGateway:
  resources:
    limits:
      memory: "512Mi"
      cpu: "0.5"
metrics:
  enabled: "true"
prometheusRule:
  enabled: "true"
  namespace: "monitoring"
