apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-externalsecret
  namespace: monitoring
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: thanos-obj-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            items:
              - key: objstore.yml
                templateAs: Values
            name: thanos-objconfig
          target: Data
  data:
  - secretKey: BUCKET_NAME
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/thanos-secrets
      metadataPolicy: None
      property: minio-bucket
  - secretKey: ACCESS_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/thanos-secrets
      metadataPolicy: None
      property: minio-access-key
  - secretKey: SECRET_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/thanos-secrets
      metadataPolicy: None
      property: minio-secret-key
