apiVersion: v1
data:
  objstore.yml: |
    type: "S3"
    config: 
      bucket: "{{ .BUCKET_NAME }}"
      endpoint: "thanos-local-cluster-minio.monitoring.svc.cluster.local:9000"
      access_key: "{{ .ACCESS_KEY }}"
      insecure: true
      secret_key: "{{ .SECRET_KEY }}"
kind: ConfigMap
metadata:
  name: thanos-objconfig
  namespace: monitoring
